CREATE TABLE IF NOT EXISTS grade_element_types (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  is_archived INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE grade_items ADD COLUMN grade_element_type_id INTEGER REFERENCES grade_element_types(id) ON DELETE SET NULL;